vim.o.termguicolors = true
-- vim.cmd.colorscheme('kanagawabones')
-- vim.cmd.colorscheme('zenwritten')
-- vim.cmd.colorscheme('forestbones')
-- vim.cmd.colorscheme('nordbones')
-- vim.cmd.colorscheme('randombones')
vim.cmd.colorscheme('zenburned')
-- vim.cmd.colorscheme('neobones')
-- vim.cmd.colorscheme('everforest')
-- vim.cmd.colorscheme('everforest')
-- vim.cmd.colorscheme('everforest')
